-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 4c90c9557da7c0d695d6a729bae8b1de4e496cbf
    hooks:
    -   id: check-json
    # Enable flake8 once python code is cleaner.
    #-   id: flake8
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    sha: 63e26cdfa5ae134c42ffd73d2978ec6248106bdd
    hooks:
    -   id: remove-crlf
